FBNEO_BURN_DIR			:= $(MAIN_FBNEO_DIR)/burn
FBNEO_BURN_DRIVERS_DIR	:= $(MAIN_FBNEO_DIR)/burn/drv
FBNEO_BURN_DEVICES_DIR	:= $(MAIN_FBNEO_DIR)/burn/devices
FBNEO_BURN_SND_DIR		:= $(MAIN_FBNEO_DIR)/burn/snd
FBNEO_BURNER_DIR		:= $(MAIN_FBNEO_DIR)/burner
FBNEO_CPU_DIR			:= $(MAIN_FBNEO_DIR)/cpu
FBNEO_GENERATED_DIR		:= $(MAIN_FBNEO_DIR)/dep/generated
FBNEO_INTERFACE_DIR		:= $(MAIN_FBNEO_DIR)/intf
FBNEO_LIB_DIR			:= $(MAIN_FBNEO_DIR)/dep/libs
FBNEO_SCRIPTS_DIR		:= $(MAIN_FBNEO_DIR)/dep/scripts
LIBRETRO_DIR			:= $(FBNEO_BURNER_DIR)/libretro
LIBRETRO_COMM_DIR		:= $(LIBRETRO_DIR)/libretro-common
UGUI_DIR				:= $(LIBRETRO_DIR)/deps/ugui

ATARI_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/atari
CAPCOM_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/capcom
CAVE_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/cave
CHANNELF_DIR			:= $(FBNEO_BURN_DRIVERS_DIR)/channelf
COLECO_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/coleco
CPS3_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/cps3
DATAEAST_DIR			:= $(FBNEO_BURN_DRIVERS_DIR)/dataeast
GALAXIAN_DIR			:= $(FBNEO_BURN_DRIVERS_DIR)/galaxian
GBA_DIR					:= $(FBNEO_BURN_DRIVERS_DIR)/gba
IREM_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/irem
KONAMI_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/konami
MD_DIR					:= $(FBNEO_BURN_DRIVERS_DIR)/megadrive
MIDWAY_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/midway
MSX_DIR					:= $(FBNEO_BURN_DRIVERS_DIR)/msx
NEOGEO_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/neogeo
NES_DIR					:= $(FBNEO_BURN_DRIVERS_DIR)/nes
PCE_DIR					:= $(FBNEO_BURN_DRIVERS_DIR)/pce
PGM_DIR					:= $(FBNEO_BURN_DRIVERS_DIR)/pgm
PGM2_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/pgm2
PRE90S_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/pre90s
PSIKYO_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/psikyo
PST90S_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/pst90s
SEGA_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/sega
SG1000_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/sg1000
SMS_DIR					:= $(FBNEO_BURN_DRIVERS_DIR)/sms
SNES_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/snes
SPECTRUM_DIR			:= $(FBNEO_BURN_DRIVERS_DIR)/spectrum
TAITO_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/taito
TOAPLAN_DIR				:= $(FBNEO_BURN_DRIVERS_DIR)/toaplan
ADSP2100_CPU_DIR		:= $(FBNEO_CPU_DIR)/adsp2100
ARM_CPU_DIR				:= $(FBNEO_CPU_DIR)/arm
ARM7_CPU_DIR			:= $(FBNEO_CPU_DIR)/arm7
ARM9_CPU_DIR			:= $(FBNEO_CPU_DIR)/arm9
E132XS_CPU_DIR			:= $(FBNEO_CPU_DIR)/e132xs
F8_CPU_DIR				:= $(FBNEO_CPU_DIR)/f8
H6280_CPU_DIR			:= $(FBNEO_CPU_DIR)/h6280
HD6309_CPU_DIR			:= $(FBNEO_CPU_DIR)/hd6309
HMCS40_CPU_DIR			:= $(FBNEO_CPU_DIR)/hmcs40
I386_CPU_DIR			:= $(FBNEO_CPU_DIR)/i386
I8039_CPU_DIR			:= $(FBNEO_CPU_DIR)/i8039
I8051_CPU_DIR			:= $(FBNEO_CPU_DIR)/i8051
I8085_CPU_DIR			:= $(FBNEO_CPU_DIR)/i8085
I8X41_CPU_DIR			:= $(FBNEO_CPU_DIR)/i8x41
KONAMI_CPU_DIR			:= $(FBNEO_CPU_DIR)/konami
M377_CPU_DIR			:= $(FBNEO_CPU_DIR)/m377
M6502_CPU_DIR			:= $(FBNEO_CPU_DIR)/m6502
M6800_CPU_DIR			:= $(FBNEO_CPU_DIR)/m6800
M6805_CPU_DIR			:= $(FBNEO_CPU_DIR)/m6805
M6809_CPU_DIR			:= $(FBNEO_CPU_DIR)/m6809
M68K_CPU_DIR			:= $(FBNEO_CPU_DIR)/m68k
MB88XX_CPU_DIR			:= $(FBNEO_CPU_DIR)/mb88xx
MIPS3_CPU_DIR			:= $(FBNEO_CPU_DIR)/mips3
MIPS3_X64_DRC_CPU_DIR	:= $(MIPS3_CPU_DIR)/x64
NEC_CPU_DIR				:= $(FBNEO_CPU_DIR)/nec
PIC16C5X_CPU_DIR		:= $(FBNEO_CPU_DIR)/pic16c5x
SH2_CPU_DIR				:= $(FBNEO_CPU_DIR)/sh2
SH4_CPU_DIR				:= $(FBNEO_CPU_DIR)/sh4
S2650_CPU_DIR			:= $(FBNEO_CPU_DIR)/s2650
T11_CPU_DIR				:= $(FBNEO_CPU_DIR)/t11
TLCS90_CPU_DIR			:= $(FBNEO_CPU_DIR)/tlcs90
TLCS900_CPU_DIR			:= $(FBNEO_CPU_DIR)/tlcs900
TMS32010_CPU_DIR		:= $(FBNEO_CPU_DIR)/tms32010
TMS34010_CPU_DIR		:= $(FBNEO_CPU_DIR)/tms34
UPD7725_CPU_DIR			:= $(FBNEO_CPU_DIR)/upd7725
UPD7810_CPU_DIR			:= $(FBNEO_CPU_DIR)/upd7810
V60_CPU_DIR				:= $(FBNEO_CPU_DIR)/v60
XA_CPU_DIR				:= $(FBNEO_CPU_DIR)/xa
Z180_CPU_DIR			:= $(FBNEO_CPU_DIR)/z180
Z80_CPU_DIR				:= $(FBNEO_CPU_DIR)/z80

ifeq ($(AUTOGEN_DATS), 1)
	FBNEO_DEFINES += -DAUTOGEN_DATS
endif

FBNEO_BURN_DRIVERS_DIRS := $(ATARI_DIR) \
	$(CAPCOM_DIR) \
	$(CAVE_DIR) \
	$(CHANNELF_DIR) \
	$(COLECO_DIR) \
	$(CPS3_DIR) \
	$(DATAEAST_DIR) \
	$(GALAXIAN_DIR) \
	$(GBA_DIR) \
	$(IREM_DIR) \
	$(KONAMI_DIR) \
	$(MD_DIR) \
	$(MIDWAY_DIR) \
	$(MSX_DIR) \
	$(NEOGEO_DIR) \
	$(NES_DIR) \
	$(PCE_DIR) \
	$(PGM_DIR) \
	$(PGM2_DIR) \
	$(PRE90S_DIR) \
	$(PSIKYO_DIR) \
	$(PST90S_DIR) \
	$(SEGA_DIR) \
	$(SG1000_DIR) \
	$(SMS_DIR) \
	$(SNES_DIR) \
	$(SPECTRUM_DIR) \
	$(TAITO_DIR) \
	$(TOAPLAN_DIR) \
	$(FBNEO_BURN_DRIVERS_DIR)

FBNEO_BURN_DIRS := $(FBNEO_BURN_DEVICES_DIR) \
	$(FBNEO_BURN_SND_DIR) \
	$(FBNEO_BURN_DRIVERS_DIRS)

FBNEO_CPU_DIRS := $(FBNEO_CPU_DIR) \
	$(ADSP2100_CPU_DIR) \
	$(ARM_CPU_DIR) \
	$(ARM7_CPU_DIR) \
	$(ARM9_CPU_DIR) \
	$(E132XS_CPU_DIR) \
	$(F8_CPU_DIR) \
	$(H6280_CPU_DIR) \
	$(HD6309_CPU_DIR) \
	$(HMCS40_CPU_DIR) \
	$(I386_CPU_DIR) \
	$(M377_CPU_DIR) \
	$(M6502_CPU_DIR) \
	$(M68K_CPU_DIR) \
	$(MB88XX_CPU_DIR) \
	$(MIPS3_CPU_DIR) \
	$(NEC_CPU_DIR) \
	$(PIC16C5X_CPU_DIR) \
	$(SH2_CPU_DIR) \
	$(SH4_CPU_DIR) \
	$(TMS34010_CPU_DIR) \
	$(UPD7725_CPU_DIR) \
	$(V60_CPU_DIR) \
	$(I8X41_CPU_DIR) \
	$(I8039_CPU_DIR) \
	$(I8051_CPU_DIR) \
	$(I8085_CPU_DIR) \
	$(KONAMI_CPU_DIR) \
	$(M6800_CPU_DIR) \
	$(M6805_CPU_DIR) \
	$(M6809_CPU_DIR) \
	$(S2650_CPU_DIR) \
	$(T11_CPU_DIR) \
	$(TLCS90_CPU_DIR) \
	$(TLCS900_CPU_DIR) \
	$(TMS32010_CPU_DIR) \
	$(UPD7810_CPU_DIR) \
	$(XA_CPU_DIR) \
	$(Z80_CPU_DIR) \
	$(Z180_CPU_DIR)

FBNEO_INTERFACE_DIRS := $(FBNEO_INTERFACE_DIR)/audio

# FBNeo framework
SOURCES_C += $(FBNEO_BURNER_DIR)/ioapi.c \
	$(FBNEO_BURNER_DIR)/unzip.c

SOURCES_CXX += $(FBNEO_BURN_DIR)/burn.cpp \
	$(FBNEO_BURN_DIR)/burn_gun.cpp \
	$(FBNEO_BURN_DIR)/burn_memory.cpp \
	$(FBNEO_BURN_DIR)/burn_sound.cpp \
	$(FBNEO_BURN_DIR)/cheat.cpp \
	$(FBNEO_BURN_DIR)/debug_track.cpp \
	$(FBNEO_BURN_DIR)/hiscore.cpp \
	$(FBNEO_BURN_DIR)/load.cpp \
	$(FBNEO_BURN_DIR)/timer.cpp \
	$(FBNEO_BURNER_DIR)/conc.cpp \
	$(FBNEO_BURNER_DIR)/dat.cpp \
	$(FBNEO_BURNER_DIR)/statec.cpp \
	$(FBNEO_BURNER_DIR)/zipfn.cpp \
	$(FBNEO_BURNER_DIR)/nvram.cpp \
	$(FBNEO_INTERFACE_DIR)/audio/aud_dsp.cpp \
	$(FBNEO_INTERFACE_DIR)/audio/lowpass2.cpp

ifneq ($(STATIC_LINKING), 1)
	SOURCES_C += $(LIBRETRO_COMM_DIR)/file/file_path.c \
		$(LIBRETRO_COMM_DIR)/file/file_path_io.c \
		$(LIBRETRO_COMM_DIR)/file/retro_dirent.c \
		$(LIBRETRO_COMM_DIR)/encodings/encoding_utf.c \
		$(LIBRETRO_COMM_DIR)/compat/compat_posix_string.c \
		$(LIBRETRO_COMM_DIR)/compat/compat_strcasestr.c \
		$(LIBRETRO_COMM_DIR)/compat/compat_strl.c \
		$(LIBRETRO_COMM_DIR)/compat/compat_strldup.c \
		$(LIBRETRO_COMM_DIR)/compat/fopen_utf8.c \
		$(LIBRETRO_COMM_DIR)/string/stdstring.c \
		$(LIBRETRO_COMM_DIR)/streams/file_stream.c \
		$(LIBRETRO_COMM_DIR)/streams/file_stream_transforms.c \
		$(LIBRETRO_COMM_DIR)/features/features_cpu.c \
		$(LIBRETRO_COMM_DIR)/file/config_file.c \
		$(LIBRETRO_COMM_DIR)/file/config_file_userdata.c \
		$(LIBRETRO_COMM_DIR)/lists/string_list.c \
		$(LIBRETRO_COMM_DIR)/memmap/memalign.c \
		$(LIBRETRO_COMM_DIR)/time/rtime.c
	ifeq ($(HAVE_UWP), 1)
		SOURCES_CXX += $(LIBRETRO_COMM_DIR)/vfs/vfs_implementation_uwp.cpp
	else
		SOURCES_C += $(LIBRETRO_COMM_DIR)/vfs/vfs_implementation.c
	endif
endif

INCLUDE_DIRS := $(FBNEO_BURNER_DIR)/win32 \
	$(LIBRETRO_COMM_DIR)/include \
	$(LIBRETRO_DIR) \
	$(FBNEO_BURN_DIR) \
	$(FBNEO_CPU_DIR) \
	$(FBNEO_BURN_SND_DIR) \
	$(FBNEO_BURN_DEVICES_DIR) \
	$(FBNEO_INTERFACE_DIR) \
	$(FBNEO_INTERFACE_DIR)/input \
	$(FBNEO_INTERFACE_DIR)/cd \
	$(FBNEO_INTERFACE_DIR)/audio \
	$(FBNEO_BURNER_DIR) \
	$(FBNEO_CPU_DIR) \
	$(F8_CPU_DIR) \
	$(HMCS40_CPU_DIR) \
	$(I8039_CPU_DIR) \
	$(I8051_CPU_DIR) \
	$(I8085_CPU_DIR) \
	$(I8X41_CPU_DIR) \
	$(M377_CPU_DIR) \
	$(M6805_CPU_DIR) \
	$(TLCS900_CPU_DIR) \
	$(TMS32010_CPU_DIR) \
	$(UPD7725_CPU_DIR) \
	$(UPD7810_CPU_DIR) \
	$(V60_CPU_DIR) \
	$(T11_CPU_DIR) \
	$(XA_CPU_DIR) \
	$(Z80_CPU_DIR) \
	$(Z180_CPU_DIR) \
	$(SH4_CPU_DIR) \
	$(PIC16C5X_CPU_DIR) \
	$(FBNEO_LIB_DIR)/zlib \
	$(FBNEO_LIB_DIR)/lib7z \
	$(FBNEO_LIB_DIR)/dr_libs \
	$(FBNEO_LIB_DIR)/stb_vorbis \
	$(FBNEO_LIB_DIR)/r8brain \
	$(CAPCOM_DIR) \
	$(KONAMI_DIR) \
	$(DATAEAST_DIR) \
	$(CAVE_DIR) \
	$(NEOGEO_DIR) \
	$(PSIKYO_DIR) \
	$(SEGA_DIR) \
	$(TOAPLAN_DIR) \
	$(TAITO_DIR) \
	$(IREM_DIR) \
	$(PCE_DIR) \
	$(GALAXIAN_DIR) \
	$(FBNEO_GENERATED_DIR) \
	$(FBNEO_LIB_DIR) \
	$(UGUI_DIR)

ARM_FLAGS =

ifeq (,$(findstring msvc,$(platform)))
	CFLAGS += -std=gnu99
endif

ifeq (,$(findstring msvc,$(platform)))
	CXXFLAGS += -std=gnu++98
endif

#ifeq ($(USE_X64_DRC), 1)
#	FBNEO_DEFINES  += -DXBYAK_NO_OP_NAMES -DMIPS3_X64_DRC
#	FBNEO_SRC_DIRS += $(MIPS3_X64_DRC_CPU_DIR)
#	ifeq (,$(findstring msvc,$(platform)))
#		CXXFLAGS += -std=gnu++11
#	endif
#else
#	ifeq (,$(findstring msvc,$(platform)))
#		CXXFLAGS += -std=gnu++98
#	endif
#endif

NEON_FLAGS=

ifeq ($(HAVE_NEON), 1)
	NEON_FLAGS = -mvectorize-with-neon-quad
	# ios and android don't support this
	ifneq (,$(findstring ios,$(platform)))
		NEON_FLAGS =
	endif
	ifneq (,$(findstring android,$(platform)))
		NEON_FLAGS =
	endif
endif

ifeq ($(SUPPORT_LARGE_FILES), 1)
	FBNEO_DEFINES += -D_FILE_OFFSET_BITS=64
endif

ifeq ($(EXTERNAL_ZLIB), 1)
	FBNEO_DEFINES += -DEXTERNAL_ZLIB
	LDFLAGS += -lz
else
	# only msvc doesn't have unistd.h ?
	ifeq (,$(findstring msvc,$(platform)))
		FBNEO_DEFINES += -DHAVE_UNISTD_H
	endif
	SOURCES_C += $(FBNEO_LIB_DIR)/zlib/inflate.c \
		$(FBNEO_LIB_DIR)/zlib/zutil.c \
		$(FBNEO_LIB_DIR)/zlib/inffast.c \
		$(FBNEO_LIB_DIR)/zlib/crc32.c \
		$(FBNEO_LIB_DIR)/zlib/adler32.c \
		$(FBNEO_LIB_DIR)/zlib/inftrees.c \
		$(FBNEO_LIB_DIR)/zlib/deflate.c \
		$(FBNEO_LIB_DIR)/zlib/trees.c
endif

ifeq ($(INCLUDE_7Z_SUPPORT), 1)
	FBNEO_DEFINES += -DINCLUDE_7Z_SUPPORT -DZ7_PPMD_SUPPORT -DZ7_ST
	SOURCES_CXX += $(FBNEO_BURNER_DIR)/un7z.cpp
	# Statically linked builds used to borrow the 7-Zip SDK from the frontend,
	# but RetroArch dropped deps/7zip in favour of its own r7z_* reader, so the
	# SzArEx_*/LookToRead2_* symbols are no longer exported. Always compile our
	# own copy: archive members are only pulled in when still undefined at link
	# time, so this cannot clash with a frontend that does provide them.
	SOURCES_C += $(FBNEO_LIB_DIR)/lib7z/7zArcIn.c \
		$(FBNEO_LIB_DIR)/lib7z/7zBuf.c \
		$(FBNEO_LIB_DIR)/lib7z/7zCrc.c \
		$(FBNEO_LIB_DIR)/lib7z/7zCrcOpt.c \
		$(FBNEO_LIB_DIR)/lib7z/7zDec.c \
		$(FBNEO_LIB_DIR)/lib7z/7zStream.c \
		$(FBNEO_LIB_DIR)/lib7z/Bcj2.c \
		$(FBNEO_LIB_DIR)/lib7z/Bra.c \
		$(FBNEO_LIB_DIR)/lib7z/Bra86.c \
		$(FBNEO_LIB_DIR)/lib7z/BraIA64.c \
		$(FBNEO_LIB_DIR)/lib7z/CpuArch.c \
		$(FBNEO_LIB_DIR)/lib7z/Delta.c \
		$(FBNEO_LIB_DIR)/lib7z/Lzma2Dec.c \
		$(FBNEO_LIB_DIR)/lib7z/LzmaDec.c \
		$(FBNEO_LIB_DIR)/lib7z/Ppmd7.c \
		$(FBNEO_LIB_DIR)/lib7z/Ppmd7Dec.c
endif

SOURCES_CXX += $(LIBRETRO_DIR)/libretro.cpp \
	$(LIBRETRO_DIR)/retro_cdemu.cpp \
	$(LIBRETRO_DIR)/retro_common.cpp \
	$(LIBRETRO_DIR)/retro_input.cpp \
	$(LIBRETRO_DIR)/retro_memory.cpp \
	$(LIBRETRO_DIR)/retro_string.cpp \
	$(LIBRETRO_DIR)/ips_manager.cpp \
	$(LIBRETRO_DIR)/romdata.cpp \
	$(LIBRETRO_DIR)/retro_pgm2_cards.cpp

SOURCES_C += $(UGUI_DIR)/ugui.c \
	$(UGUI_DIR)/ugui_textbox.c \
	$(UGUI_DIR)/font_8x8.c \
	$(UGUI_DIR)/SourceHanSansCN_Medium_13X17.c \
	$(LIBRETRO_DIR)/ugui_tools.c

SOURCES_C += $(FBNEO_LIB_DIR)/libchdr/libchdr_flac.c

ifeq ($(INCLUDE_CHD_SUPPORT), 1)
	FBNEO_DEFINES += -DINCLUDE_CHD_SUPPORT -DUSE_LIBRETRO_VFS
	SOURCES_CXX += $(FBNEO_INTERFACE_DIR)/cd/cd_chd.cpp
	ifeq ($(CHD_LIBRETRO), 1)
		SOURCES_C += $(LIBRETRO_COMM_DIR)/formats/libchdr/libchdr_chd.c \
			$(LIBRETRO_COMM_DIR)/formats/libchdr/libchdr_zlib.c \
			$(LIBRETRO_COMM_DIR)/formats/libchdr/libchdr_huffman.c \
			$(LIBRETRO_COMM_DIR)/formats/libchdr/libchdr_bitstream.c \
			$(LIBRETRO_COMM_DIR)/encodings/encoding_deflate.c \
			$(LIBRETRO_COMM_DIR)/formats/libchdr/libchdr_cdrom.c
		INCLUDE_DIRS += $(LIBRETRO_COMM_DIR)/include/libchdr/
	else
		FBNEO_DEFINES += -DCHDR_SYSTEM_ZLIB
		SOURCES_C += $(FBNEO_LIB_DIR)/libchdr/libchdr_chd.c \
			$(FBNEO_LIB_DIR)/libchdr/libchdr_codec_zlib.c \
			$(FBNEO_LIB_DIR)/libchdr/libchdr_codec_cdzl.c \
			$(FBNEO_LIB_DIR)/libchdr/libchdr_bitstream.c \
			$(FBNEO_LIB_DIR)/libchdr/libchdr_huffman.c \
			$(FBNEO_LIB_DIR)/libchdr/libchdr_codec_huff.c \
			$(FBNEO_LIB_DIR)/libchdr/libchdr_codec_flac.c \
			$(FBNEO_LIB_DIR)/libchdr/libchdr_codec_lzma.c \
			$(FBNEO_LIB_DIR)/libchdr/libchdr_codec_zstd.c \
			$(FBNEO_LIB_DIR)/libchdr/libchdr_codec_cdlz.c \
			$(FBNEO_LIB_DIR)/libchdr/libchdr_codec_cdfl.c \
			$(FBNEO_LIB_DIR)/libchdr/libchdr_codec_cdzs.c \
			$(FBNEO_LIB_DIR)/libchdr/libchdr_cdrom.c \
			$(FBNEO_LIB_DIR)/lzma/libchdr_lzma.c \
			$(FBNEO_LIB_DIR)/zstd/zstddeclib.c
		INCLUDE_DIRS += $(FBNEO_LIB_DIR)/libchdr/include/ \
			$(FBNEO_LIB_DIR)/lzma/
	endif
endif

# GIT HASH
GIT_VERSION := $(shell git rev-parse --short HEAD || echo unknown)
ifneq ($(GIT_VERSION),unknown)
	GIT_DATE := $(shell git log -1 --format="%at" | xargs -I{} date -d @{} +%y%m%d)
	CXXFLAGS += -DGIT_DATE=\"$(GIT_DATE)\" -DGIT_VERSION=\"GIT$(GIT_VERSION)\"
endif
